### ISSUE TITLE
Zend DB conflict ranges

### ISSUE THREAD

**Issue by SamBurns-awin** [Roave/SecurityAdvisories#10]
With reference to https://github.com/Roave/SecurityAdvisories/commit/410eb5b0f3c8b93e3f4ee838b5a15f7808a0d0aa , which versions of zendframework/zend-db are actually allowed?  Are any of them secure at all?

**Comment by Ocramius** [comment]
I still have to tag `"zendframework/zend-db"` `2.3.5` and `2.3.6`, but I didn't get to do it yet.

**Comment by SamBurns-awin** [comment]
Is there a specific security problem with zendframework/zend-db 2.2.9, or has it just been added because it is unsupported?  It was the last version supporting PHP 5.3.3.

**Comment by Ocramius** [comment]
I simply don't yet have a `2.2.10` release for `zendframework/zend-db`.

**Comment by SamBurns-awin** [comment]
What is the nature of the security flaw in ZF2's DB implementation? Is it just that there are no versions that can be used with roave/security-advisories in our composer file, or is there a serious security issue with all releases of zendframework/zend-db?

**Comment by Ocramius** [comment]
This has been fixed today by releasing the split components of ZF2: https://packagist.org/packages/zendframework/zend-db
