### ISSUE TITLE
installation problems with guzzlehttp

### ISSUE THREAD

**Issue by vodnicearv** [Roave/SecurityAdvisories#101]
Problem 1
    - guzzlehttp/guzzle is locked to version 7.4.4 and an update of this package was not requested.
    - roave/security-advisories dev-latest conflicts with guzzlehttp/guzzle <6.5.8|>=7,<7.4.5.
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].

composer json:
"guzzlehttp/guzzle": "^7.0.1",

**Comment by Ocramius** [comment]
This is intentional, since guzzle up to 7.4.5 is affected by security issues.

Please read this project's documentation.
