### ISSUE TITLE
typo3/cms needs to be in sync with typo3/cms-core

### ISSUE THREAD

**Issue by simonschaufi** [Roave/SecurityAdvisories#105]
typo3/cms-core: `>=9,<9.5.37` is wrong. It needs to be `>=9,<9.5.29`. The other version constraints also needs to match.

**Comment by froschdesign** [comment]
> typo3/cms-core: `>=9,<9.5.37` is wrong.

See:

- [Extended Long Term Support](https://typo3.com/services/extended-support-elts)
- https://get.typo3.org/release-notes/9.5.37
- …

**Comment by Ocramius** [comment]
This repository only merges published advisories: you will need to find the faulty CVE publication, and backtrack from there.
