### ISSUE TITLE
Need release, please

### ISSUE THREAD

**Issue by igormukhingmailcom** [Roave/SecurityAdvisories#11]
Hi.

Can you release please?
Now you haven't any tags.

So we need to write `dev-master` at `composer.json`, but this is not good idea + have problems with `minimum-stability`.

Thank you a lot.
Nice work!

**Comment by veewee** [comment]
Hi @igormukhingmailcom ,

This package will remain at dev-master. Please read:
https://github.com/Roave/SecurityAdvisories#stability

**Comment by igormukhingmailcom** [comment]
@veewee Thank you. Thats right.
