### ISSUE TITLE
Vulnerable package not in security advisories

### ISSUE THREAD

**Issue by 8ctopus** [Roave/SecurityAdvisories#113]
While looking at my apache logs, I found bots scanning the following package which is most likely vulnerable to some sort of attack which is not yet in the security advisories.

https://packagist.org/packages/htmlawed/htmlawed

I opened an issue with the package itself: https://github.com/kesar/HTMLawed/issues/24

**Comment by Ocramius** [comment]
This repository will pick it up as soon as a GitHub advisory is published: nothing to do here 😁
