### ISSUE TITLE
All Craft 3 installs (craftcms/cms) recently flagged as insecure

### ISSUE THREAD

**Issue by angrybrad** [Roave/SecurityAdvisories#117]
Context here: https://github.com/craftcms/cms/issues/13336#issuecomment-1599661035

Recently all Craft 3 versions using this package have been (incorrectly) flagged as insecure. I _think_ it's coming from the unbounded `< 4.2.1` constraint at the end of https://github.com/Roave/SecurityAdvisories/blob/latest/composer.json#L94

But as far as I can tell, that unbound constraint has been there for 9 months: https://github.com/Roave/SecurityAdvisories/commit/4ed8a24bbb14c02aae12f8ec386e3e2804f58198

Mainly just looking for help on how to interpret and correct what we're seeing.

**Comment by Ocramius** [comment]
@angrybrad seems like it's caused by this range: https://github.com/advisories/GHSA-3x74-v64j-qc3f

**Comment by Ocramius** [comment]
Note: fix the advisory accordingly, and it will be fixed here too 😁

**Comment by angrybrad** [comment]
@Ocramius thank you! PR fix for the GHSA here: https://github.com/github/advisory-database/pull/2443
