### ISSUE TITLE
Craft 3 installs (craftcms/cms) flagged as insecure

### ISSUE THREAD

**Issue by LauraMontgomery** [Roave/SecurityAdvisories#118]
This seems to be a problem at keeps re-appearing.
Last flagged on 22nd June: [https://github.com/Roave/SecurityAdvisories/issues/117](https://github.com/Roave/SecurityAdvisories/issues/117)

**Comment by xabbuh** [comment]
github/advisory-database#2443 has been merged only 13 hours ago. Maybe it just takes some time to be visible here too.

**Comment by Ocramius** [comment]
I'd check if:

 1. the advisory DB is cached
 2. there are more advisories declaring the version constraint invalid

Closing here though: the root cause is not in this repository.
