### ISSUE TITLE
Laravel illuminate/view 9 and 10 not authorized

### ISSUE THREAD

**Issue by rmn-eloha-jouny** [Roave/SecurityAdvisories#121]
Hello !

I'm looking at `illuminate/view` in your `composer.json` and versions `^9.0` and `^10.0` are not allowed. But when I'm looking in the database of PHP security advisories, it doesn't seems to have any issues for this version : https://github.com/FriendsOfPHP/security-advisories/tree/master/illuminate/view

Do we need to do something in your package ?

**Comment by Ocramius** [comment]
`^9.0` and `^10.0` are allowed:

https://github.com/Roave/SecurityAdvisories/blob/5cfed3056826da5ee547ebb4b58e39bc4ca14d6e/composer.json#L242
