### ISSUE TITLE
PHP CodeSniffer alternative

### ISSUE THREAD

**Issue by alexandr-macovchin** [Roave/SecurityAdvisories#124]
Bug report? no
Feature request? no
Library version | x.y.z

The package squizlabs/PHP_CodeSniffer is abandoned and will no longer be supported.
@Roave you have plans to migrate to the other code-style tool/project?

Article about the fate of PHP CodeSniffer.
https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

New package or the @jrfnl(profile: https://github.com/jrfnl)

Regards, Alexandr.

**Comment by Ocramius** [comment]
@alexandr-macovchin we'll just use the [new package name](https://github.com/PHPCSStandards/PHP_CodeSniffer), which is compatible.

You'd just need to replace the reference in your `composer.json`

**Comment by alexandr-macovchin** [comment]
Ok, thanks for the clarification.

**Comment by alexandr-macovchin** [comment]
@Ocramius thnak you

**Comment by jrfnl** [comment]
FYI: it currently looks like the Packagist name may not change after all. As per the announcement: wait until there has been a release until making any changes. The release will contain any relevant info for users to be able to switch over.

**Comment by alexandr-macovchin** [comment]
@jrfnl yep. thnx
