### ISSUE TITLE
Strange behavior with laminas/laminas-diactoros

### ISSUE THREAD

**Issue by charithar** [Roave/SecurityAdvisories#130]
I have PHP 7.4 (yes it's old but required for legacy system) and composer 2.7 in my environment. I have the laminas/laminas-diactoros 2.8.0 installed in the project. When I try to add roave/security-advisories package it reports following error.

 - laminas/laminas-diactoros is locked to version 2.8.0 and an update of this package was not requested.
    - roave/security-advisories dev-master conflicts with laminas/laminas-diactoros <2.18.1|==2.19|==2.20|==2.21|==2.22|==2.23|>=2.24,<2.24.2|>=2.25,<2.25.2.
    - Root composer.json requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].

What can I do about it? Thanks.

**Comment by Ocramius** [comment]
What's the weird behaviour?

**Comment by charithar** [comment]
> What's the weird behaviour?

Sorry. I prematurely submitted the question previously. Updated the question again with details. again

**Comment by Ocramius** [comment]
Why not? Some advisories are very limited in scope, and the ranges there don't seem to overlap 🤔

**Comment by Ocramius** [comment]
Btw, the error in OP is legit: you should upgrade

**Comment by charithar** [comment]
Seems like that there is a problem with version of laminas/laminas-diactoros package. Their github page doesn't show a 2.8.x version but such version gets installed when it's specified. Anyway, thank you very much for the reply. I'll need to update the PHP version to get rid of the conflict warning.

**Comment by Ocramius** [comment]
It's there?

 * https://github.com/laminas/laminas-diactoros/releases 
 * https://github.com/laminas/laminas-diactoros/releases/tag/2.8.0

**Comment by charithar** [comment]
> It's there?
> 
> * https://github.com/laminas/laminas-diactoros/releases
> * https://github.com/laminas/laminas-diactoros/releases/tag/2.8.0

Yeah. I managed to install it forcefully before. It should not trigger the conflict according to the constraints above I guess but it did. Not sure why.

**Comment by Ocramius** [comment]
> and an update of this package was not requested. 

It was probably too many arguments (or too restrictive arguments) passed to `composer update` :)
