### ISSUE TITLE
This project should be politically agnostic

### ISSUE THREAD

**Issue by A-Kun** [Roave/SecurityAdvisories#133]
I currently use this project in many projects, including enterprise projects, but I’m becoming a bit uncomfortable as more political messages are being added to README. 

For one, this can become unsustainable should the next conflict occurs. The list of political messages will grow longer, and partisanship disputes may occur (e.g. “why did you support them but not us?”). 

For two, a project with many political messages makes me worried that a maintainer with potential political motivations could launch a supply chain attack, especially for a project on the topic of security and is not versioned. 

Technology should be about the technology itself, and should be politically agnostic.

**Comment by Ocramius** [comment]
Nope, piss off.
