### ISSUE TITLE
Conflict with drupal/core-recommended

### ISSUE THREAD

**Issue by Ihnatsevych** [Roave/SecurityAdvisories#135]
New version conflict with drupal core recommended ">=8,<=11.0.4":
https://github.com/Roave/SecurityAdvisories/commit/4d2e39c44028ba729fe50efdf731d3d2ede4046b

**Comment by Ocramius** [comment]
This repo only follows the upstream CVEs: Drupal is marked insecure there.

https://github.com/advisories/GHSA-mg8j-w93w-xjgc

This repo will update automatically when the upstream CVEs are updated.
