### ISSUE TITLE
I'm sorry, is this an Open-Source or some dude's home project?

### ISSUE THREAD

**Issue by LeTraceurSnork** [Roave/SecurityAdvisories#136]
![image](https://github.com/user-attachments/assets/4b75626b-70a7-4282-8428-5ea7ad80fcf4)
First of all, who do you think you are?

Second, is this Open Source or a project by some left-leaning student?

Third, since we’re discussing security, has anyone thought about the safety of this package itself? Especially in light of the 2022 news about npm packages specifically targeting software from Russia and Belarus. Or is this some sort of Orwellian Open Source—open to some sort of chosen-ones, while the rest are supposed to sit under the table?

Fourth, what’s with the childish/dictatorial behavior—pushing your agenda and closing issues to comments? Excuse me, is this Guantanamo speaking?

p.s. `Piss off`, lol, seriously?
I'm not a lot into open-source community, maybe I don't get smth, but last time I've said smth similar to my classmate in person, I've been punched in the face

**Comment by Ocramius** [comment]
Given how much you asked for it, I'm glad to be able to say to you as well, with confidence: piss off.
