### ISSUE TITLE
Revert simplesamlphp/simplesamlphp?

### ISSUE THREAD

**Issue by sandermarechal** [Roave/SecurityAdvisories#137]
I think that the conflict for simplesamlphp should be reverted back to:

```
"simplesamlphp/simplesamlphp": "<1.18.6"
```

See also: https://github.com/github/advisory-database/pull/5047

simplesamlphp/simplesamlphp itself is *not* vulnerable to GHSA-j5g2-q29x-cw3h, only the simplesamlephp/saml2 is. The developer made that security advisory for people who do *not* use composer and who rely on a tarball based on the included composer.lock file. roave/security-advisories is for people who *do* use composer. And they can use the fixed simplesamlphp/saml2 with older simplesamlphp/simplesamlphp versions.

**Comment by Ocramius** [comment]
Bring this up with the upstream advisories, please: this repository follows them, and the range will change automatically within 1h of the change landing.

**Comment by sandermarechal** [comment]
It seems like the upstream author does not want to retract the invalid advisory. See my PR there and the discussion: https://github.com/github/advisory-database/pull/5047

**Comment by Ocramius** [comment]
I'm a bit puzzled by 2 bogus advisories landing in the same upstream at the same time: see https://github.com/Roave/SecurityAdvisoriesBuilder/pull/756 and GHSA-7q22-x757-cmgc / GHSA-cg28-v4wq-whv5

Is there some sort of nest of bad advisory handling awareness?

**Comment by sandermarechal** [comment]
I think so. The Symfony people can't help it that someone filed bogus CVEs (someone padding their security researcher resumé?). The situation with SimpleSAMLphp is a tad different. I can sort of understand the author wanting a GHSA for the many people who install from tarball. It's just that that GHSA is explicitly *not* for versions installed with Composer. So maybe roave/security-advisories should ignore that one?

**Comment by Ocramius** [comment]
@sandermarechal in that case, see https://github.com/Roave/SecurityAdvisoriesBuilder/pull/756

Happy to accept a patch there too.

**Comment by sandermarechal** [comment]
Awesome, I just created a PR: https://github.com/Roave/SecurityAdvisoriesBuilder/pull/757
