### ISSUE TITLE
This Package Doesn't Support Laravel 11

### ISSUE THREAD

**Issue by JohnGuoy** [Roave/SecurityAdvisories#138]
My environment:
Laravel version: 11.26
PHP version: 8.2

When I attempt to install the roave/security-advisories package using the following command:
$ composer require --dev roave/security-advisories:dev-latest

I encounter the following error:
./composer.json has been updated
Running composer update roave/security-advisories
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework is locked to version v11.26.0 and an update of this package was not requested.
    - roave/security-advisories dev-latest conflicts with laravel/framework <6.20.45|>=7,<7.30.7|>=8,<8.83.28|>=9,<9.52.17|>=10,<10.48.23|>=11,<11.31.
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].

It seems like the roave/security-advisories package isn't compatible with Laravel 11. Can anyone help resolve this issue when possible? Thanks!

**Comment by jdreesen** [comment]
It says that you have `laravel/framework` installed in version `v11.26.0` but `roave/security-advisories` conflicts with `laravel/framework` versions `>=11,<11.31` which means you need to update `laravel/framework` to `v11.31` or later.

Try with `composer require --dev roave/security-advisories:dev-latest --update-with-all-dependencies`
