### ISSUE TITLE
Match more version constraints

### ISSUE THREAD

**Issue by Ocramius** [Roave/SecurityAdvisories#15]
The `VersionConstraint` currently allows matching [only a very limited type of constraint](https://github.com/Roave/SecurityAdvisories/blob/6964ea81b8a454a35a12002b33db659b8b4bf782/build-advisories/src/Roave/SecurityAdvisories/VersionConstraint.php#L10-L12)

This may be improved, but it is not completely necessary

**Comment by stof** [comment]
There is no usage of more complex ranges in the security-advisory database repository, and the validation of Yaml files would not allow to use more complex operators currently, so there won't be.

Btw, using the semver operators for advisories does not make sense: once you report an advisory, the following versions are fixed, so the upper bound is almost never the next major version

**Comment by Ocramius** [comment]
@stof I'm more worried about people that may start adding `-RC`, `~`, `^`, `-DEV`, `-BETA`, `-ALPHA`

**Comment by Ocramius** [comment]
Agree on the upper bound, I just coded the logic in the domain as per the concepts it abstracts to avoid confusion.

**Comment by stof** [comment]
@Ocramius ``~`` and ``^`` are the semver operators I'm talking about.

**Comment by Ocramius** [comment]
So why wouldn't I allowed to mark all of a component after a certain version unsafe to use?

**Comment by stof** [comment]
@Ocramius because this would mean that you plan to never fix a security issue. this does not make sense.

**Comment by Ocramius** [comment]
It kinda does for stuff such as Guzzle, that has been renamed a dozen times

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Ocramius** [comment]
Moved to https://github.com/Roave/SecurityAdvisoriesBuilder/issues/7
