### ISSUE TITLE
Merge consecutive ranges

### ISSUE THREAD

**Issue by stof** [Roave/SecurityAdvisories#21]
Once #14 is done, there is another case where we can merge ranges: consecutive ones. This happens when the upper bound of 1 range is the same than the lower bound of the other range, and at least one of the range includes the bound:

- ``>=2.1,<2.2 | >=2.2,<2.2.5`` => ``>=2.1,<2.2.5``
- ``>=2.1,<=2.2 | >2.2,<2.2.5`` => ``>=2.1,<2.2.5``
- ``>=2.1,<=2.2 | >=2.2,<2.2.5`` => ``>=2.1,<2.2.5`` (may be catched by #14 already, not sure)
- ``>=2.1,<2.2 | >2.2,<2.2.5`` => no change as 2.2.0 is not matched by ranges

**Comment by Ocramius** [comment]
> (may be catched by #14 already, not sure)

I explicitly wanted to avoid that until I have a VO that represents the inclusiveness/exclusiveness of a boundary end.

For now, I simply made the logic so that only completely included edges are considered in #14.

**Comment by Ocramius** [comment]
Implemented a VO called `Boundary` that encapsulates limit, inclusivity and version.

See #30.

Closing here, moving discussion there, if needed.
