### ISSUE TITLE
Add drupal/core

### ISSUE THREAD

**Issue by davidbarratt** [Roave/SecurityAdvisories#29]
Could you please add [drupal/core](https://packagist.org/packages/drupal/core) ? It's a subtree split of [drupal/drupal](https://packagist.org/packages/drupal/drupal) so it should be the same.

**Comment by Ocramius** [comment]
Was it submitted to https://github.com/FriendsOfPHP/security-advisories?

**Comment by davidbarratt** [comment]
Nope.. I'll add there. 

Thanks!
