### ISSUE TITLE
Constraints should be sorted when dumping the composer.json file

### ISSUE THREAD

**Issue by stof** [Roave/SecurityAdvisories#31]
To avoid useless diffs between versions, constraints should be sorted before dumping them, to ensure a consistent dump.
Sorting by lower bound (or by upper bound, whichever you prefer) seems logical.

**Comment by Ocramius** [comment]
The fact that revisions are merged now reduced the issue by a lot: is this still worth fixing?

**Comment by Ocramius** [comment]
Closing - `won't fix`.
