### ISSUE TITLE
Tag this package to prevent inspection warning

### ISSUE THREAD

**Issue by FrankGiesecke** [Roave/SecurityAdvisories#34]
Inspection of the `composer.json` shows up the warning `The version constraint has not upper bound - this is not a good idea.`

It would be nice to have some tags, so that we can use the `@stable` constraint.

**Comment by Ocramius** [comment]
@FrankGiesecke it is impossible to tag this package, because any tagged version would cause the composer SAT solver to go to older versions when new conflicts are introduced.

See also https://github.com/Roave/SecurityAdvisories/tree/7cd88c8d4e4e6b483633bb13c35bcec95fd6cd4c#stability
