### ISSUE TITLE
Sort constraints to prevent useless diffs

### ISSUE THREAD

**Issue by Ocramius** [Roave/SecurityAdvisories#40]
Commits like https://github.com/Roave/SecurityAdvisories/commit/a88d5f2e09a349e2d2f1dcde218860ede463a4f1 are quite frequent, and caused by different globbing/sorting of configurations, upgrades in components that do the YAML parsing and so on.

Basic sorting (can be very simple) of the constraints would prevent this in future.

I think @stof reported this previously.

**Comment by Jean85** [comment]
I was confused at first, but maybe we should specify that this issue is related to https://github.com/Roave/SecurityAdvisoriesBuilder, right?

**Comment by Ocramius** [comment]
Groan, yes, my mistake :|

**Comment by Ocramius** [comment]
As per https://github.com/Roave/SecurityAdvisories/commit/f793fe6ff54acabd9bc9f76f4a9ad3c89a68c789 - this is now fixed. Thanks @Jean85!

**Comment by Ocramius** [comment]
Handled in https://github.com/Roave/SecurityAdvisoriesBuilder/pull/5
