### ISSUE TITLE
Is not compatible with the latest symfony flex

### ISSUE THREAD

**Issue by zerkms** [Roave/SecurityAdvisories#49]
I'm not sure whether it's `Roave/SecurityAdvisories` or `composer` bug, but let's try to start research from here.

Versions details:
os: ubuntu 18.04 (just installed)
php 7.2.7 (the official ubuntu repository) with `php-curl`, `php-xml` and `php-zip` installed additionally
composer `1.7.2 2018-08-16 16:57:12`

Steps to reproduce:

1. Create an empty symfony flex project:

        cd /tmp
        composer create-project symfony/website-skeleton bug

1. Add `roave/security-advisories` dependency

        cd bug
        composer require --dev roave/security-advisories:dev-master

Expected: all should be good

Actual:

```
Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for __root__ No version set (parsed as 1.0.0) -> satisfiable by __root__[No version set (parsed as 1.0.0)].
    - roave/security-advisories dev-master conflicts with __root__[No version set (parsed as 1.0.0)].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
```

**Comment by Ocramius** [comment]
No `__root__` defined here: I suggest you open a composer bug...

**Comment by zerkms** [comment]
Christophe confirmed it's a composer-related bug, closing it here, thanks :-)
