### ISSUE TITLE
"composer outdated" command reports this package as outdated in CI jobs

### ISSUE THREAD

**Issue by Wirone** [Roave/SecurityAdvisories#51]
Since there are no stable releases, only `dev-master`, our CI jobs are failed in weird way.

When I run `composer outdated --direct --minor-only --strict` locally, I have 0 exit code and everything is OK. In Gitlab CI job I get:

```
roave/security-advisories dev-master ! dev-master 6acf968 Prevents installation of composer packages with known security vulnerabilities: no API, simply require it
```

AFAIS 6acf968 is latest commit and we have it in `composer.lock` so I don't get why COmposer complains about it.

Anyway, do you consider providing stable releases? This shouldn't add much to maintaining time (just create tags) and it would bring added value:
- Do not depend on unstable package (`dev-master`) in projects
- `composer outdated` would report this package in the same way like others

If all tags would be in `1.x` branch, constraint `~1.0` would work the same as `dev-master`. So this is only up to maintainers it they want to provide tags (releases).

**Comment by Ocramius** [comment]
This package *CANNOT* have stable releases by design.

See `README.md`.


Scenario:

 * you have `roave/security-advisories:~1.0` as a dependency
 * you have `zendframework/zend-session:2.8.1` as a dependency
 * `roave/security-advisories:1.0.0` contains `zendframework/zend-session:<2.8.0` as conflict
 * `roave/security-advisories:1.0.1` contains `zendframework/zend-session:<2.9.0` as conflict

If you run `composer update` you won't get a failure (as per design of this package), but you will get an outdated version of `roave/security-advisories` installed.

**Comment by Ocramius** [comment]
Closing as `invalid`. The discussion on how the CLI command above is supposed to behave should be moved to `composer/composer`.

**Comment by Wirone** [comment]
@Ocramius I don't agree with you. This package COULD HAVE stable releases, if documentation would encourage users to add `composer outdated` and `composer why-not` to their development flow (first one in CI probably).

In scenario above, if `roave/security-advisories` wouldn't be updated, `composer outdated` would inform about it. `composer why-not roave/security-advisories 1.0.1` would answer why it can't be updated (too low version of `zendframework/zend-session`). User should then update dependencies in a way that `roave/security-advisories` could be installed in newest version.

Anyway, thanks for quick feedback.

**Comment by Ocramius** [comment]
No, the idea of the package is to integrate with as minimum effort as possible within existing workflows. It is designed to be a hot (always live) exclusion map to be used at any composer SAT solver run.

If a second CLI command was required, this would have much less impact on the ecosystem, as users would need to explicitly design a workflow to check the security of their packages.

**Comment by Ocramius** [comment]
Note: the design of the package is done in such a way that it is very unlikely that a user can avoid it. In this way, even less experienced composer users benefit from it and learn about the security issues in their configuration.

**Comment by Wirone** [comment]
Ok, I understand your point of view and acknowledge that it won't change. Fair enough.

**Comment by jdreesen** [comment]
The [latest composer version](https://github.com/composer/composer/releases/tag/1.8.0) (1.8.0) supports ignoring packages in the `outdated` command:

> Added `--ignore` to `outdated` command to pass one or more packages that you do not want to be listed

Maybe this fixes your problem?

**Comment by Wirone** [comment]
@jdreesen I know, I'm the author of that change :grin: But I don't want to ignore this package.

The problem is different. We had cache in CI with outdated `vendor` dir. I thought `composer outdated` uses `composer.lock`, not actual files. We now know how to handle it :)

**Comment by Majkl578** [comment]
> This package CANNOT have stable releases by design.

I think it can, i.e. date-based tags. Users would be told to require `"roave/security-advisories": "*"`´instead of dev-master. This solves the issue of depending on unstable package and provides the same guarantee as dev-master.

**Comment by Ocramius** [comment]
Only if I delete older tags, which is not gonna help anyway.

**Comment by Majkl578** [comment]
Why would you have to delete old tags? You don't delete old commits either. What am I missing?

**Comment by Ocramius** [comment]
The SAT always picks a set of available versions, then combines them to find compatible permutations until a working one is found: this package only ever has **ONE** available version by design, explicitly to prevent SAT fallbacks.
