### ISSUE TITLE
Please tag a version

### ISSUE THREAD

**Issue by digitall-it** [Roave/SecurityAdvisories#55]
Please tag a `v1.0` version. The version constraint `dev-master` has no upper bound - this is not a good idea. See [Why are unbound version constraints a bad idea?](https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md) for more information.

**Comment by jdreesen** [comment]
This package will remain at dev-master. 
Please read: https://github.com/Roave/SecurityAdvisories#stability

See also: #7, #11, #34, #39, #51

**Comment by Ocramius** [comment]
Thanks for responding in detail, @jdreesen 👍
