### ISSUE TITLE
[BUGFIX] Sponsoring over github is not possible

### ISSUE THREAD

**Issue by tomasnorre** [Roave/SecurityAdvisories#56]
As a grateful user, when I click at <3 Sponsor, I want to be able to say thanks with a contributions/some money etc, so that the developers know there work is appreciated. 

![Screenshot 2019-07-29 at 12 37 51](https://user-images.githubusercontent.com/1212481/62042217-de8aee80-b1fd-11e9-96bc-18ddc3c2ffe6.png)

**Comment by Ocramius** [comment]
Yep, I rolled in when they announced, but my account is not yet enabled 😞
