### ISSUE TITLE
Conflict with replacing packing

### ISSUE THREAD

**Issue by JurRutten** [Roave/SecurityAdvisories#61]
I'm having an issue with a packages that replace zendframework1
shardj/zf1-future 1.16.2

Should securityadvisories check replacing packages?
This seems like a bug, or is this a composer issue?

**Comment by Ocramius** [comment]
> I'm having an issue with a packages that replace zendframework1

What issue?

 > Should securityadvisories check replacing packages?

All packages should be checked

**Comment by JurRutten** [comment]
The issue is, that it conflicts with this package.
But the package itself is not in this 'conflict' section of the securityadvisories composer.json file.
Does composer 'conflict' also check the 'replacing' section of the  'shardj/zf1-future' composer.json file?
If so, that doesn't seem right to me ...

**Comment by Ocramius** [comment]
IF `shardj/zf1-future` provides a version that `provides` or `replaces` a `zendframework/zendframework1` version that has a known published security issue, then it should correctly conflict, as `shardj/zf1-future` declares that it provides exactly that same version of `zendframework/zendframework1`.

It should probably declare that it replaces a newer version of `zendframework/zendframework1` instead.

**Comment by JurRutten** [comment]
Just found this thread on the zf1-future package --> https://github.com/Shardj/zf1-future/pull/39
