### ISSUE TITLE
PLease add Laminas as zendframework changed their brand to Laminas

### ISSUE THREAD

**Issue by developer-devPHP** [Roave/SecurityAdvisories#63]
zendframework changed their project and now it is called `Laminas`, so Please also add Laminas issues too.
After this changes all packages called `zendframework`, `zfcampus`, moved to their `Laminas ` paths and current packages marked as archive.

`For example`
```
"zendframework/zend-cache" now "laminas/laminas-cache"

"zendframework/zend-captcha" now "laminas/laminas-captcha"
```
etc ...

**Comment by Ocramius** [comment]
This already happens implicitly, since the exact versions of `laminas/*` provide (and replace) versions of `zendframework/*`, so the SAT mechanism already knows which versions to exclude for `laminas/*` based on `zendframework/*` advisories.
