### ISSUE TITLE
Update `illuminate / cookie`

### ISSUE THREAD

**Issue by tp** [Roave/SecurityAdvisories#67]
After the Laravel Cookie incident, I think the conflict with https://github.com/illuminate/cookie needs to be updated.

Related: https://blog.laravel.com/laravel-cookie-security-releases

**Comment by Ocramius** [comment]
@tp this repo only contains aggregated advisories from upstream sources: you will probably need to report any problem in specific packages in `friendsofphp/security-advisories` or to the GitHub security advisories.

**Comment by tp** [comment]
Thanks for explaining @Ocramius 

So there is an upstream PR open already: https://github.com/FriendsOfPHP/security-advisories/pull/478

Is there anything more that needs to be done here then once that is merged? Else we can close this.

**Comment by Ocramius** [comment]
Nope, it syncs here automatically, once an hour 👍

Closing here for now
