### ISSUE TITLE
Backlink to packagist

### ISSUE THREAD

**Issue by KarelWintersky** [Roave/SecurityAdvisories#75]
Please, add to 'about' widget of github repo (right block) link to packagist (https://packagist.org/packages/roave/security-advisories )

**Comment by Ocramius** [comment]
The source URL already points back here, to the only README too?

**Comment by KarelWintersky** [comment]
![изображение](https://user-images.githubusercontent.com/2164874/119359390-3b4c7880-bcb2-11eb-99e1-881a76f98d45.png)

Like here:
https://github.com/ArrisFramework/Arris.Toolkit.Nginx have a link to packagist page: https://packagist.org/packages/karelwintersky/arris.toolkit.nginx

and vice versa

**Comment by Ocramius** [comment]
That is covered by the "downloads" link: 
<img width="89" alt="Capture" src="https://user-images.githubusercontent.com/154256/119361432-f3c2ee00-bcab-11eb-9815-9c0fc3c3df18.PNG">

**Comment by KarelWintersky** [comment]
small iconized link... not obvious, IMHO. 

Really wontfix?

**Comment by Ocramius** [comment]
Feel free to send a patch for an improved to the README, if needed, but I
don't see a reason to give packagist more weight than it already gets

**Comment by KarelWintersky** [comment]
It's not a README change, but a repo settings. Can't send patch/pr.

**Comment by froschdesign** [comment]
@KarelWintersky 
The link is for the project's website, but there is no website. And packagist.org does not add value for the user, except for some statistics.

**Comment by KarelWintersky** [comment]
wont discuss
