### ISSUE TITLE
phpmyadmin/phpmyadmin 1.0.0+no-version-set conflicts with roave/security-advisories dev-latest.

### ISSUE THREAD

**Issue by williamdes** [Roave/SecurityAdvisories#76]
Failures: https://github.com/williamdes/phpmyadmintest/runs/2713378511
https://github.com/phpmyadmin/phpmyadmin/commits/master?before=1ac5820cdf73d3c1136e5e733a4d4746c01805d2+35&branch=master

You can see `b4d6282376d2f4a9ccd851daa333d9acd39c0b12` passes and just after `3706c1fcd1eab234dc3bd1007232c684be19704f` does not

```
  Problem 1
    - phpmyadmin/phpmyadmin is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - phpmyadmin/phpmyadmin 1.0.0+no-version-set conflicts with roave/security-advisories dev-latest.
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].
```

Composer bug or something else ?

This only happens on my custom multi arch setup using alpine

**Comment by Ocramius** [comment]
This seems to be related with the branch name in use: probably headless
checkout.

"No branch" is interpreted as 1.0.0, which is old/vulnerable.

You may want to perhaps do a checkout of a specific tag?

**Comment by williamdes** [comment]
I just tried locally using `git switch --detach HEAD~1` and rm vendor and lock, doing a `composer update` worked perfectly :/

Then I tried on an alpine container just like in the CI, and it failed

But: adding `git` `apk add git` made `composer update` pass.

Conclusion: I think we will have users complaining at us because of that, do you think it could be fixed in some way ?

**Comment by Ocramius** [comment]
> Conclusion: I think we will have users complaining at us because of that, do you think it could be fixed in some way ?

IMO not fixable: `composer/composer` infers the current version from `git`, and when `git` is not available, it will infer `1.0.0+no-version-set`, which is not really a version.

Installing `git` seems like an acceptable trade-off, as pretty much every system that runs `composer` will get `git` at some point to do operations like `git clone` anyway :shrug: 

Alternatively, I would try `composer create-project phpmyadmin/phpmyadmin`, which should try to scaffold a project from a specifically looked up version.

Closing here, as it is really not an issue with this repo, but rather with how phpmyadmin suggests being installed.

**Comment by williamdes** [comment]
Thank you for the feedback @Ocramius 
I hope after 5.2 is released (in a long time) everything works well, because we have users using the STABLE branch to do installs, but of course they are supposed to have git at this point so it should be okay

**Comment by williamdes** [comment]
For example I can not deploy phpMyAdmin on GoogleCloudEngine because of that
```
  Problem 1
    - Installation request for phpmyadmin/phpmyadmin No version set (parsed as 1.0.0) -> satisfiable by phpmyadmin/phpmyadmin[No version set (parsed as 1.0.0)].
    - roave/security-advisories dev-latest conflicts with phpmyadmin/phpmyadmin[No version set (parsed as 1.0.0)].
    - Installation request for roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].
```

**Comment by Ocramius** [comment]
Yeah, but that's not solvable here: you need it to recognize the exact tag/version, which is the correct resolution.
