### ISSUE TITLE
Please add support for guzzlehttp/guzzle v 7.3

### ISSUE THREAD

**Issue by Axent96** [Roave/SecurityAdvisories#82]
guzzlehttp/guzzle v6.x is old.
support for guzzlehttp/guzzle v 7.x is in need

**Comment by Ocramius** [comment]
7.x seems supported?

https://github.com/Roave/SecurityAdvisories/blob/2253b042c4cf1a9413f44a1c224ef2f705517bfb/composer.json#L120
