### ISSUE TITLE
Typosquatting - symfont/process

### ISSUE THREAD

**Issue by Danack** [Roave/SecurityAdvisories#83]
Does this project list stuff like tpyo-squatting e.g. symfont/process vs symfony/process

https://www.kernelmode.blog/typosquatting-malware-found-in-composer-repository/

**Comment by Ocramius** [comment]
Nay, also unlikely to support permutations, as it would explide the repository size

**Comment by Ocramius** [comment]
You can report `symfont/process:*` as a security issue to GitHub: it will be picked up.

**Comment by Danack** [comment]
cool.

**Comment by Ocramius** [comment]
Meanwhile: https://github.com/Roave/SecurityAdvisories/commit/506ae662828c26fbf1436954388191c452897bde
