### ISSUE TITLE
Typo in package name "symfont/process"

### ISSUE THREAD

**Issue by craiglondon** [Roave/SecurityAdvisories#84]
I think there is a typo in this package name

        "symfont/process": ">=0,<4"

I think it is supposed to be

        "symfony/process": ">=0,<4"

**Comment by orklah** [comment]
I think it's the result of #83

**Comment by Ocramius** [comment]
It's intentional: the security issue is caused by literally somebody releasing `symfoty/process` (typo intentional), and having people mis-type it, and installing a malicious package.
