### ISSUE TITLE
Conflict with silverstripe/admin

### ISSUE THREAD

**Issue by rosiemck** [Roave/SecurityAdvisories#85]
- roave/security-advisories dev-latest conflicts with silverstripe/admin 1.9.0.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.9.0-rc1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.9.0-beta1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.9.0-alpha1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.8.1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.8.0.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.8.0-rc1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.8.0-beta1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.7.4.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.7.3.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.7.2.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.7.1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.7.0.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.7.0-rc1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.7.0-beta1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.6.4.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.6.3.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.6.2.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.6.1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.6.0.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.6.0-rc1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.6.0-beta1.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.5.2.
    - roave/security-advisories dev-latest conflicts with silverstripe/admin 1.5.1.

**Comment by Ocramius** [comment]
The issue is with https://github.com/advisories/GHSA-j66h-cc96-c32q

I suggest reaching out to who reported that

**Comment by dizzystuff** [comment]
Hi this has targeted the wrong package. silverstripe/admin is in version 1.x, whereas it appears that silverstripe/framework <4.8.1 was the intended target. The related [update/commit](https://github.com/Roave/SecurityAdvisories/commit/bad3752fd78f4a07acb24e56fec0366aa711f150) now completely prevents the installation of any version of modern SilverStripe. Please advise whether a PR is the best way for me to submit a fix for this, or some alternate method.

**Comment by Ocramius** [comment]
Heyo,

this package only replicates what is announced on the github advisories: you will need to request an edit on https://github.com/advisories/GHSA-j66h-cc96-c32q

**Comment by dizzystuff** [comment]
Ok thanks
