### ISSUE TITLE
Advisory for laravel/framework <= 8.70.2 has been withdrawn

### ISSUE THREAD

**Issue by nick-smit** [Roave/SecurityAdvisories#87]
Hi,

[This advisory](https://github.com/advisories/GHSA-364w-9g92-3grq) has been withdrawn. So i think the `laravel/framework` package conflict should be reverted to the previous value.

**Comment by Ocramius** [comment]
I think the concept of "withdrawn" wasn't existing at the time when we implemented `GetAdvisoriesFromGithubApi`.

Can you send a patch+test against this?

https://github.com/Roave/SecurityAdvisoriesBuilder/blob/7830d9ec618d84f73515075070d413cc48f2cdd6/src/Roave/SecurityAdvisories/AdvisorySources/GetAdvisoriesFromGithubApi.php#L37-L53

**Comment by nick-smit** [comment]
Offcourse, here you go: https://github.com/Roave/SecurityAdvisoriesBuilder/pull/456

**Comment by Ocramius** [comment]
Solved by https://github.com/Roave/SecurityAdvisoriesBuilder/pull/456

Need to wait a bit and see if that actually fixed the issue - come back in an hour :D

**Comment by nick-smit** [comment]
It seems to have worked. 

Thanks for reviewing the changes!

**Comment by Ocramius** [comment]
Ref: https://github.com/Roave/SecurityAdvisories/commit/8a0da9e2c9a96425395e0af80bd3aece26576245

**Comment by Ocramius** [comment]
Thanks @nick-smit!
