### ISSUE TITLE
Java equivalent of `roave/security-advisories`

### ISSUE THREAD

**Issue by carusogabriel** [Roave/SecurityAdvisories#88]
Ciao 👋🏼 

we use this library here at @usabilla with our PHP projects but with recent additions to the architecture, we now have Java dependencies to manage (amazing, no?). 

We wonder if the maintainers also touch Java codebases in their daily jobs, and have some advice for us on what to use that yields similar results as `roave/security-advisories` 😁

Thank you!

**Comment by Ocramius** [comment]
Probably something like a maven dependency? :thinking: 

I don't know if there's a concept like `composer/composer`'s `conflict` declaration there.

**Comment by Ocramius** [comment]
Closing here: as much as I'd like to help, I'm unable to do so here.

**Comment by carusogabriel** [comment]
> Probably something like a maven dependency?

Gradle in our case, but yes - that conflicts with non-secure versions.

 > I don't know if there's a concept like composer/composer's conflict declaration there.

We neither, but thanks for give a hint :)

> Closing here: as much as I'd like to help, I'm unable to do so here.

No worries, thanks!
