### ISSUE TITLE
Unclear why laravel-filemanager is marked as insecure

### ISSUE THREAD

**Issue by MaxKorlaar** [Roave/SecurityAdvisories#89]
Hi,

I noticed that unisharp/laravel-filemanager has been added to the conflicts in the following commit: https://github.com/Roave/SecurityAdvisories/commit/5369c567667640bc617d0c6b1ba7c156128ccec5. The commit description links to a codeigniter security advisory, which doesn't seem relevant for this package. I've noticed the following issue on the filemanager's repository: https://github.com/UniSharp/laravel-filemanager/issues/1096, does it have anything to do with this?

**Comment by Ocramius** [comment]
Related: https://github.com/Roave/SecurityAdvisoriesBuilder/issues/451

As for the specific advisory, see https://github.com/advisories/GHSA-f8x6-m9f5-ffp8

**Comment by MaxKorlaar** [comment]
Thanks! I missed that one. Too bad it's not shown on https://github.com/UniSharp/laravel-filemanager/security/advisories, which is where I looked first.

**Comment by Ocramius** [comment]
The advisory at https://github.com/advisories/GHSA-f8x6-m9f5-ffp8 is not linked to the repo.

**Comment by MaxKorlaar** [comment]
Noticed, thanks again!

**Comment by mfn** [comment]
I too was surprised how @Ocramius even found that advisory 🤷‍♀️

**Comment by Ocramius** [comment]
Please read https://github.com/Roave/SecurityAdvisoriesBuilder/issues/451

This contains all the advisories at https://github.com/advisories, and `composer.json` is re-generated every hour.

**Comment by mfn** [comment]
Thank you 🙏🏼
