### ISSUE TITLE
Using old guzzlehttp/psr7

### ISSUE THREAD

**Issue by leeyuentuen** [Roave/SecurityAdvisories#99]
Hi,
I need to use the old guzzlehttp/psr7 package (1.8.3) https://github.com/guzzle/psr7/issues/489#issuecomment-1073343836
but after the latest update of security advisories it required 1.8.4

which gives me now the error:

> #11 36.60     - Root composer.json requires guzzlehttp/psr7 1.8.3 -> satisfiable by guzzlehttp/psr7[1.8.3].
> #11 36.60     - roave/security-advisories dev-master conflicts with roave/security-advisories dev-master.
> #11 36.60     - Root composer.json requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].

**Comment by Ocramius** [comment]
@leeyuentuen this package is explicitly designed to deny usage of insecure versions of a library: that's its core feature.

**Comment by leeyuentuen** [comment]
> @leeyuentuen this package is explicitly designed to deny usage of insecure versions of a library: that's its core feature.

indeed, i  saw it, we will make the change at our our side
